#pragma once

enum ShaderType { NO_SHADE, TERRAIN, LAMP, ADD, LOWPASS_X, LOWPASS_Y, PLAIN, THRES };

enum TextureType {
  OFFICE_WALL,
  GRASS,
  SKYBOX_SKY,
  SKYBOX_CITY,
  DIRT,
  OFFICE_FLOOR,
  CONCRETE,
  OFFICE_CEILING,
  WHITE,
  OFFWHITE,
  BLACK,
  CARTON_TEX
};

enum ModelType { SKYBOX, SPHERE, CHAIR, CARTON, SQUARE };

enum TileType { EMPTY, PILLAR, LIGHT };
enum RoomTypes { RAND_PILLARS };
