#pragma once

enum ShaderType { NO_SHADE, TERRAIN, LAMP };

enum TextureType { OFFICE_WALL, GRASS, SKYBOX_SKY, SKYBOX_CITY, DIRT, OFFICE_FLOOR, CONCRETE, OFFICE_CEILING, WHITE };

enum ModelType { SKYBOX, SPHERE };